apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cert-secret
type: kubernetes.io/tls
data:
  tls.crt: |
        {{ .Values.certificate.crt }}
  tls.key: |
        {{ .Values.certificate.tlsKey }}