apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
    mongo-root-username: {{ .Values.mongoSecret.rootUsername | b64enc }}
    mongo-root-password: {{ .Values.mongoSecret.rootPassword | b64enc }}
